# Application definition
# https://docs.djangoproject.com/en/dev/ref/settings/#installed-apps
INSTALLED_APPS = [
    "admin_auto_filters",
    "admin_interface",
    "colorfield",
    "corsheaders",
    "django_ace",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.humanize",
    "whitenoise.runserver_nostatic",
    "django_filters",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "rest_framework",
    "drf_spectacular",
    "crispy_forms",
    # "crispy_tailwind",
    "crispy_daisyui",
    # "debug_toolbar",
    "tailwind",
    "theme",
    "storages",
    "django_htmx",
    # "easy_thumbnails",
    # "image_cropping",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_browser_reload",
    "admin.apps.AdminConfig",
    "system.apps.SystemConfig",
    "access.apps.AccessConfig",
    "pages.apps.PagesConfig",
    "content.apps.ContentConfig",
    "api.apps.ApiConfig",
    "blog.apps.BlogConfig",
    "connect.apps.ConnectConfig",
    # "support.apps.SupportConfig",
]
