from project.settings.environment import ENV

AWS_ACCESS_KEY_ID = ENV.str("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = ENV.str("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = ENV.str("AWS_STORAGE_BUCKET_NAME")
AWS_DEFAULT_REGION = ENV.str("AWS_DEFAULT_REGION")

USE_S3_FOR_STATIC_FILES = ENV.bool("USE_S3_FOR_STATIC_FILES", True)

AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
MEDIA_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN
AWS_S3_FILE_OVERWRITE = False
