# Generated by Django 5.0.3 on 2025-06-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_example_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
