# Generated by Django 5.0.3 on 2025-06-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_example_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
